"""create search history table

Revision ID: 12c0b98ff310
Revises: 2b7f9d8e5a1c
Create Date: 2026-02-07 13:30:32.258878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12c0b98ff310'
down_revision: Union[str, None] = '2b7f9d8e5a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('messages', 'tool_calls')
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_mcp_servers_user_id'), 'user_mcp_servers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mcp_servers_user_id'), table_name='user_mcp_servers')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.add_column('messages', sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('messages', 'images',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
