"""add custom_instructions to users

Revision ID: 1438e3bc91b5
Revises: token_blacklist_table
Create Date: 2026-01-02 22:30:32.880741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1438e3bc91b5'
down_revision: Union[str, None] = 'token_blacklist_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_instructions')
    # ### end Alembic commands ###
