"""Add UserMCPServer model

Revision ID: 331904c9c90e
Revises: fc65a962d838
Create Date: 2024-10-16 12:30:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "331904c9c90e"
down_revision = "fc65a962d838"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_mcp_servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("server_name", sa.String(), nullable=True),
        sa.Column("server_config", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_mcp_servers_id"), "user_mcp_servers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_mcp_servers_server_name"),
        "user_mcp_servers",
        ["server_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_mcp_servers_server_name"), table_name="user_mcp_servers"
    )
    op.drop_index(op.f("ix_user_mcp_servers_id"), table_name="user_mcp_servers")
    op.drop_table("user_mcp_servers")
    # ### end Alembic commands ###
