"""Add UserAPIKey model

Revision ID: 9790ecd14c4e
Revises:
Create Date: 2024-10-16 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9790ecd14c4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("encrypted_key", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_api_keys_id"), "user_api_keys", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_api_keys_model_name"),
        "user_api_keys",
        ["model_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_api_keys_model_name"), table_name="user_api_keys")
    op.drop_index(op.f("ix_user_api_keys_id"), table_name="user_api_keys")
    op.drop_table("user_api_keys")
    # ### end Alembic commands ###
